name: TotalFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: 5.0
description: Plugin for the Total Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
