name: LambdaMinecraftBETA
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the FreedomOP wing of LambdaMinecraft.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza, Pramire]

# plugin.yml is no longer used to define commands.
