name: UnraveledMCMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the UnraveledMC server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, UMC-Essentials]
authors: [Madgeek1450, Prozza, PinchTheFinch, CreeperSeth, aggelosQQ]

# plugin.yml is no longer used to define commands.
