name: AlexFreedomMod_BETA
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for the Alex Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, AlexTheMurderer]

# plugin.yml is no longer used to define commands.
