name: TotalFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for the Total Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
