name: AlexFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 6.0beta
description: Plugin for AlexFreedom!
softdepend: [AF-BukkitTelnet, AF-WorldEdit, AF-Essentials]
authors: [Madgeek1450, Savnith, Prozza]

# plugin.yml is no longer used to define commands.
