name: ImmaFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 3.1
description: Plugin for the ImmaFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, DisguiseCraft]
authors: [Madgeek1450, Prozza, tylerhyperHD, AwesomePinch, aggelosQQ, OxLemonxO, Savnith]

# plugin.yml is no longer used to define commands.
