name: TotalFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.9
description: Plugin for the Total Freedom server.
authors: [StevenLawson / Madgeek1450, JeromSar / DarthSalamon]
commands:
  adminmode:
    description: Console-only command - Close server to non-superadmins.
    usage: /<command> [on | off]
  cage:
    description: Superadmin command - Place a cage around someone.
    usage: /<command> <partialname> <off | [[outermaterial] [innermaterial]]>
  cake:
    description: Superadmin command - For the people that are still alive.
    usage: /<command>
  cartsit:
    description: Sit in nearest minecart. If target is in a minecart already, they will disembark.
    usage: /<command> [partialname]
  clearall:
    description: Superadmin command - Removes all entities, nicks and disguises
    usage: /<command>
  cmdlist:
    description: Show all commands for all server plugins.
    usage: /<command>
  creative:
    description: Quickly change your own gamemode to creative, or define someone's username to change theirs.
    usage: /<command> [partialname]
  csay:
    description: Telnet command - Send a chat message with chat formatting over telnet.
    usage: /<command> <message...>
  deop:
    description: Superadmin command - Deop a player
    usage: /<command> <playername>
  deopall:
    description: Superadmin command - Deop everyone on the server.
    usage: /<command>
  dispfill:
    description: Fill nearby dispensers with a set of items of your choice.
    usage: /<command> <radius> <comma,separated,items>
  doom:
    description: Owner command - For the bad Superadmins.
    usage: /<command> <playername>
  enchant:
    description: Enchant items.
    usage: /<command> <list | addall | reset | add <name> | remove <name>>
  expel:
    description: Superadmin command - Push people away from you.
    usage: /<command> [radius] [strength]
  explosives:
    description: Superadmin command - Enable/disable explosives and set effect radius.
    usage: /<command> <on | off> [radius]
  fireplace:
    description: Superadmin command - Enable/disable fire placement.
    usage: /<command> <on | off>
  firespread:
    description: Superadmin command - Enable/disable fire spread.
    usage: /<command> <on | off>
  flatlands:
    description: Goto the flatlands.
    usage: /<command>
  fluidspread:
    description: Superadmin command - Enable/disable fluid spread.
    usage: /<command> <on | off>
  fr:
    description: Superadmin command - Freeze players (toggles on and off).
    usage: /<command> [target | purge]
  fuckoff:
    description: You'll never even see it coming.
    usage: /<command>
  gadmin:
    description: Superadmin command - Use admin commands on someone by hash. Use mode 'list' to get a player's hash. Other modes are kick, nameban, ipban, ban, op, deop, ci
    usage: /<command> [list | [<kick | nameban | ipban | ban | op | deop | ci> <targethash>] ]
  gcmd:
    description: Superadmin command - Send a command as someone else.
    usage: /<command> <fromname> <outcommand>
  glist:
    description: Superadmin command - Ban/Unban any player, even those who are not logged in anymore.
    usage: /<command> <purge | <ban | unban> <username>>
  gtfo:
    description: Superadmin command - Makes someone GTFO (deop and ip ban by username).
    usage: /<command> <partialname>
  halt:
    description: Superadmin command - Halts a player
    usage: /<command> <<partialname> | all | purge | list>
  kicknoob:
    description: Superadmin command - Kick all non-superadmins on server.
    usage: /<command>
  landmine:
    description: Set a landmine trap.
    usage: /<command>
  lavadmg:
    description: Superadmin command - Enable/disable lava damage.
    usage: /<command> <on | off>
  lavaplace:
    description: Superadmin command - Enable/disable lava placement.
    usage: /<command> <on | off>
  list:
    description: Lists the real names of all online players.
    usage: /<command>
    aliases: [who]
  lockup:
    description: Console command - Block target's minecraft input. This is evil, and I never should have wrote it.
    usage: /<command> <all | purge | <<partialname> on | off>>
  moblimiter:
    description: Owner command - Controll mob rezzing parameters.
    usage: /<command> <on|off|setmax <count>|dragon|giant|ghast|slime>
  mp:
    description: Purge all mobs in all worlds.
    usage: /<command>
  mp44:
    description: Superadmin Command - Modern weaponry, FTW. Use 'draw' to start firing, 'sling' to stop firing.
    usage: /<command> <draw | sling>
  nether:
    description: Goto the nether.
    usage: /<command>
  nonuke:
    description: Superadmin command - Attempt to detect "invisible griefers" and "nukers".
    usage: /<command> <on | off> [range] [blockrate]
  onlinemode:
    description: Console command - Switch server online-mode on and off.
    usage: /<command> <on | off>
  op:
    description: Makes a player operator
    usage: /<command> <playername>
  opall:
    description: Superadmin command - Op everyone on the server, optionally change everyone's gamemode at the same time.
    usage: /<command> [-c | -s]
  ops:
    description: Superadmin command - Manage operators
    usage: /<command> [count | list | purge]
  opme:
    description: Superadmin command - Automatically ops user.
    usage: /<command>
  orbit:
    description: Superadmin command - POW!!! Right in the kisser! One of these days Alice, straight to the Moon!
    usage: /<command> <target> [power]
  permban:
    description: Manage permanently banned players and IPs
    usage: /<command> <list | reload>
  potion:
    description: Manipulate potion effects. Duration is measured in server ticks (~20 ticks per second).
    usage: /<command> <list | clear [target_name] | add <type> <duration> <amplifier> [target_name]>
  prelog:
    description: Superadmin command - Enable/disable the command prelogger. When this is on, logs will be filled with many duplicate messages.
    usage: /<command> <on | off>
  protectarea:
    description: Superadmin command - Protect areas so that only superadmins can directly modify blocks in those areas. WorldEdit and other such plugins might bypass this.
    usage: /<command> <list | clear | remove <label> | add <label> <radius>>
  qdeop:
    description: Quick De-Op - deop someone based on a partial name.
    usage: /<command> <partialname>
  qop:
    description: Quick Op - op someone based on a partial name.
    usage: /<command> <partialname>
  radar:
    description: Shows nearby people sorted by distance.
    usage: /<command> [range]
  rank:
    description: Shows your rank.
    usage: /<command>
  rawsay:
    description: Owner Command - Broadcasts the given message with no extra formatting.
    usage: /<command> <message>
  rd:
    description: Superadmin command - Remove all projectiles, dropped items, experience orbs, primed explosives, and minecarts. Minecarts are optional, based on if "carts" is included after the command.
    usage: /<command> <carts>
  ro:
    description: Superadmin Command - Remove all blocks of a certain type in the radius of certain players.
    usage: /<command> <block> [radius (default=50)] [player]
  saconfig:
    description: Owner command - Manage superadmins.
    usage: /<command> <list | clean | <add|delete> <username>>
  say:
    description: Broadcasts the given message as the console, includes sender name.
    usage: /<command> <message>
  setlevel:
    description: Sets your expierence level.
    usage: /<command> [level]
  setspawnworld:
    description: Superadmin Command - Set world spawnpoint.
    usage: /<command>
  smite:
    description: Superadmin Command - Someone being a little bitch? Smite them down...
    usage: /<command> [playername]
  ender:
    description: Goto the ender / "The End".
    usage: /<command>
  status:
    description: Show misc. server info.
    usage: /<command>
  stfu:
    description: Superadmin Command - Mutes a player with brute force.
    usage: /<command> [<player> | list | purge | all]
    aliases: [mute]
  stop:
    description: Superadmin command - Kicks everyone and stops the server.
    usage: /<command>
  survival:
    description: Quickly change your own gamemode to survival, or define someone's username to change theirs.
    usage: /<command> [partialname]
  tempban:
    description: Superadmin Command - Temporarily ban someone.
    usage: /<command> [playername] [duration] [reason]
#  terminal:
#    description: Execute a system command.
#    usage: /<command> <syscmd>
  tfbanlist:
    description: Shows all banned player names. Superadmins may optionally use 'purge' to clear the list.
    usage: /<command> [purge]
  tfipbanlist:
    description: Shows all banned IPs. Superadmins may optionally use 'purge' to clear the list.
    usage: /<command> [purge]
  tossmob:
    description: Throw a mob in the direction you are facing when you left click with a stick.
    usage: /<command> <mobtype [speed] | off | list>
  uall:
    description: Superadmin command - Undisguises all players
    usage: /<command>
  waterplace:
    description: Superadmin command - Enable/disable water placement.
    usage: /<command> <on | off>
  whitelist:
    description: Superadmin command - Manage the whitelist.
    usage: /<command> <on | off | list | count | add <player> | remove <player> | addall | purge>
  wildcard:
    description: Superadmin command - Run any command on all users, username placeholder = ?.
    usage: /<command> [fluff] ? [fluff] ?
  wipeflatlands:
    description: Owner command - Wipe the flatlands map. Requires manual restart after command is used.
    usage: /<command>
#  ziptool:
#    description: Owner command - Zip and unzip files.
#    usage: /<command> <zip <directory>> | <unzip <file>>
